package bean;
// Generated 19/11/2017 18:52:48 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Exame generated by hbm2java
 */
public class Exame  implements java.io.Serializable {


     private Integer excod;
     private String exdescricao;
     private Set consultas = new HashSet(0);

    public Exame() {
    }

	
    public Exame(String exdescricao) {
        this.exdescricao = exdescricao;
    }
    public Exame(String exdescricao, Set consultas) {
       this.exdescricao = exdescricao;
       this.consultas = consultas;
    }
   
    public Integer getExcod() {
        return this.excod;
    }
    
    public void setExcod(Integer excod) {
        this.excod = excod;
    }
    public String getExdescricao() {
        return this.exdescricao;
    }
    
    public void setExdescricao(String exdescricao) {
        this.exdescricao = exdescricao;
    }
    public Set getConsultas() {
        return this.consultas;
    }
    
    public void setConsultas(Set consultas) {
        this.consultas = consultas;
    }




}


