package bean;
// Generated 19/11/2017 18:52:48 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Medico generated by hbm2java
 */
public class Medico  implements java.io.Serializable {


     private int medcrm;
     private Especialidades especialidades;
     private String mednome;
     private String medcpf;
     private String medfone;
     private String medendereco;
     private Set consultas = new HashSet(0);

    public Medico() {
    }

	
    public Medico(int medcrm, Especialidades especialidades, String mednome) {
        this.medcrm = medcrm;
        this.especialidades = especialidades;
        this.mednome = mednome;
    }
    public Medico(int medcrm, Especialidades especialidades, String mednome, String medcpf, String medfone, String medendereco, Set consultas) {
       this.medcrm = medcrm;
       this.especialidades = especialidades;
       this.mednome = mednome;
       this.medcpf = medcpf;
       this.medfone = medfone;
       this.medendereco = medendereco;
       this.consultas = consultas;
    }
   
    public int getMedcrm() {
        return this.medcrm;
    }
    
    public void setMedcrm(int medcrm) {
        this.medcrm = medcrm;
    }
    public Especialidades getEspecialidades() {
        return this.especialidades;
    }
    
    public void setEspecialidades(Especialidades especialidades) {
        this.especialidades = especialidades;
    }
    public String getMednome() {
        return this.mednome;
    }
    
    public void setMednome(String mednome) {
        this.mednome = mednome;
    }
    public String getMedcpf() {
        return this.medcpf;
    }
    
    public void setMedcpf(String medcpf) {
        this.medcpf = medcpf;
    }
    public String getMedfone() {
        return this.medfone;
    }
    
    public void setMedfone(String medfone) {
        this.medfone = medfone;
    }
    public String getMedendereco() {
        return this.medendereco;
    }
    
    public void setMedendereco(String medendereco) {
        this.medendereco = medendereco;
    }
    public Set getConsultas() {
        return this.consultas;
    }
    
    public void setConsultas(Set consultas) {
        this.consultas = consultas;
    }




}


